data = read.csv("filtered_data.csv")
png(filename='plot4.png',width=480,height=480,units='px',bg='transparent')
par(mfrow=c(2,2))
with(data, {
	plot(dateTime, Global_active_power, xaxt="n", type="1", ylab="Global Active Power", axis="")	
	lines(dateTime, Global_active_power)
	axis(1, dateTime, format(as.Date(as.character(dateTime)), "%a"))
})
with(data, {
	plot(dateTime, Voltage, xaxt="n", ylab="Voltage", xlab='datetime', type='l')
	lines(dateTime, Voltage)
	axis(1, dateTime, format(as.Date(as.character(dateTime)), "%a"))
})
with(data, {
	plot(dateTime, Sub_metering_1, type='l', xaxt="n", xlab='', ylab="Energy sub metering")
	lines(dateTime, Sub_metering_1, type='l')
	lines(dateTime, Sub_metering_2, type='l', col='red')
	lines(dateTime, Sub_metering_3, type='l', col='blue')
	axis(1, dateTime, format(as.Date(as.character(dateTime)), "%a"))
	legend('topright', legend=c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'), lwd='1', col=c('black', 'red', 'blue'))
})
with(data, {
	plot(dateTime, Global_reactive_power, xaxt="n", xlab='datetime', ylab="Global_reactive_power", type='l')
	lines(dateTime, Global_reactive_power)
	axis(1, dateTime, format(as.Date(as.character(dateTime)), "%a"))
})
x<-dev.off()